name: vault read passwords

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  read-secret:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: read secret from vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://mills-now-discovery-devoted.trycloudflare.com
          method: JWT
          role: github-deploy #role assigned to the GitHub job in the vault policy

          secrets: | #this is the list of secrets to read from vault, the format is: <vault path>#<vault key>=<env variable name>
            secret/data/github username | USERNAME
            secret/data/github password | PASSWORD

      - name: Show retrieved secrets
        run: |
          echo "Username: $USERNAME"
          echo "Password: $PASSWORD"
          echo "Secrets retrieved successfully."
