name: CI secret scanning with Gitleaks

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main
    - 'hotfix/*'
    - 'feature/*'

permissions:
  contents: read #reads the contents of the repository
  security-events: write #allows the workflow to create and manage security events, such as alerts for detected secrets.

jobs:
  secret-scanning:
    name: Secret Scanning with Gitleaks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Install Gitleaks
      run: |
        curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/v8.28.0/install.sh | sh -s -- -b /usr/local/bin

    - name: Verify installation & Configuration files
      run: |
        gitleaks version

        if [ -f .gitleaks.toml ]; then
          echo ".gitleaks.toml exists"
        else
          echo ".gitleaks.toml does not exist"

          exit 1 #exit if the configuration file is not found, preventing the workflow from proceeding without the necessary configuration for Gitleaks.
        fi

    #Full repo scan for secrets on push to main branch
    - name: Gitleaks - scans full history for secrets
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #uses: gitleaks/gitleaks-action@v2
      #with:
      #  config-path: .gitleaks.toml
      #  fail: true
      run: |
        echo "Scanning entire repo history for secrets on push to main branch ..."

        #upload main scan
        gitleaks detect --source=. --config=.gitleaks.toml --report-format=json --report-path=gitleaks-report-main.json --verbose --exit-code 1
        #the source parameter specifies the directory to scan (in this case, the current directory), and the report is generated in JSON format and saved to gitleaks-report.json. The --exit-code 1 option ensures that the workflow fails if any secrets are detected.

    - name: Upload Gitleaks for main branch scan
      if: always() && github.event_name == 'push' && github.ref == 'refs/heads/main' #ensures that the report is uploaded regardless of whether the previous steps succeeded or failed, allowing for review of the scan results even if secrets were detected.
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report-main-${{ github.sha }}
        path: gitleaks-report-main.json
        if-no-files-found: ignore #this option prevents the workflow from failing if no secrets are found and the report file is not generated. It allows the workflow to continue without errors in such cases.
        #github.sha is a unique identifier for the commit that triggered the workflow. It is used to name the uploaded artifact, which contains the Gitleaks report for that specific commit.

        #Scan staged diff for secrets on pull requests
    - name: Gitleaks - scan staged diff (PR only)
      if: github.event_name == 'pull_request'
      run: |

        echo "Scanning staged diff for secrets in pull request ..."

        #fetch the base branch of the pull request to compare against the current branch, ensuring that the scan only checks for secrets introduced in the changes of the pull request.
        git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1 #this command fetches the base branch of the pull request from the remote repository, allowing the workflow to compare the changes in the pull request against the base branch.

        echo "Scanning commits introduced by this PR ..."

        #run gitleaks to scan the staged diff between the base branch and the current branch, using the specified configuration file (.gitleaks.toml) to define the rules for detecting secrets. The --log-opts option specifies the range of commits to analyze, which is set to compare the base branch of the pull request with the current HEAD.
        gitleaks detect --log-opts="origin/${{ github.base_ref }}..HEAD" --report-format=json --report-path=gitleaks-report-pr.json --config=.gitleaks.toml --verbose --exit-code 1

    - name: Upload Gitleaks report
      if: always() && github.event_name == 'pull_request' #ensures that the report is uploaded regardless of whether the previous steps succeeded or failed, allowing for review of the scan results even if secrets were detected.
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report-pr-${{ github.sha }}
        #github.sha is a unique identifier for the commit that triggered the workflow. It is used to name the uploaded artifact, which contains the Gitleaks report for that specific commit.
        path: gitleaks-report-pr.json
        if-no-files-found: ignore #this option prevents the workflow from failing if no secrets are found and the report file is not generated. It allows the workflow to continue without errors in such cases.
